version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: mongodb-springProject
    ports:
      - "27016:27017"
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    networks:
      - mongo-db-network

networks:
  mongo-db-network:
    driver: bridge
